version: "3.8"

services:

  database:
    build: ./database
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"  

  backend:
    image: backend:latest
    build: ./back_end
    ports:
      - 8000:8000
    depends_on:
      - database
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"

  frontend:
    image: frontend:latest
    build: ./front_end
    ports:
      - 80:80
    links:
      - backend:backend
