-- Créer la table
CREATE TABLE IF NOT EXISTS stats (
    year INT DEFAULT 0,
    week VARCHAR(255) DEFAULT '',
    display_name VARCHAR(255) DEFAULT '',
    first_name VARCHAR(255) DEFAULT '',
    nick_name VARCHAR(255) DEFAULT '',
    last_name VARCHAR(255) DEFAULT '',
    team VARCHAR(255) DEFAULT '',
    position VARCHAR(5) DEFAULT '',
    playerId VARCHAR(50) DEFAULT '',
    defensive_assists INT DEFAULT 0,
    defensive_interceptions INT DEFAULT 0,
    defensive_interceptions_yards INT DEFAULT 0,
    defensive_forced_fumble INT DEFAULT 0,
    defensive_passes_defensed INT DEFAULT 0,
    defensive_sacks FLOAT DEFAULT 0.0,
    defensive_safeties INT DEFAULT 0,
    defensive_solo_tackles INT DEFAULT 0,
    defensive_total_tackles INT DEFAULT 0,
    defensive_tackles_for_a_loss INT DEFAULT 0,
    touchdowns_defense INT DEFAULT 0,
    fumbles_lost INT DEFAULT 0,
    fumbles_total INT DEFAULT 0,
    kickoff_returns_touchdowns INT DEFAULT 0,
    kickoff_returns_yards INT DEFAULT 0,
    kick_returns INT DEFAULT 0,
    kick_returns_average_yards FLOAT DEFAULT 0.0,
    kick_returns_long INT DEFAULT 0,
    kick_returns_touchdowns INT DEFAULT 0,
    kick_returns_yards INT DEFAULT 0,
    kicking_fg_att INT DEFAULT 0,
    kicking_fg_long INT DEFAULT 0,
    kicking_fg_made INT DEFAULT 0,
    kicking_xk_att INT DEFAULT 0,
    kicking_xk_made INT DEFAULT 0,
    opponent_fumble_recovery INT DEFAULT 0,
    passing_attempts INT DEFAULT 0,
    passing_completions INT DEFAULT 0,
    passing_interceptions INT DEFAULT 0,
    passing_touchdowns INT DEFAULT 0,
    passing_yards INT DEFAULT 0,
    punt_returns INT DEFAULT 0,
    punt_returns_average_yards FLOAT DEFAULT 0.0,
    punt_returns_long INT DEFAULT 0,
    punt_returns_touchdowns INT DEFAULT 0,
    punting_average_yards FLOAT DEFAULT 0.0,
    punting_long INT DEFAULT 0,
    punting_punts INT DEFAULT 0,
    punting_punts_inside_20 INT DEFAULT 0,
    receiving_receptions INT DEFAULT 0,
    receiving_target INT DEFAULT 0,
    receiving_touchdowns INT DEFAULT 0,
    receiving_yards INT DEFAULT 0,
    rushing_attempts INT DEFAULT 0,
    rushing_average_yards FLOAT DEFAULT 0.0,
    rushing_touchdowns INT DEFAULT 0,
    rushing_yards INT DEFAULT 0,
    total_points_scored INT DEFAULT 0
);

-- Copier les données depuis le CSV
COPY stats FROM '/docker-entrypoint-initdb.d/statsNFL.csv' DELIMITER ',' CSV HEADER;

